name: context

on: ['push']

jobs:
  contextJob:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        env:
          MY_ENV: ${{ github.actions }}
          MY_ACTOR: ${{ github.actor }}
        run: |
         echo "$MY_ENV"
         echo "$MY_ACTOR"