name: dependent job

on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  job2: 
    needs: job1
    steps: 
      - name: step 2
        run : echo "this is job2"
  job1:
    steps:
      - name: step1
        run: echo "this is job1"