name: dependentJob

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hellow"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "World"