name: Multi-event
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  multieventJob:
    runs-on: ubuntu-latest
    steps:
      - name: "echo basic infos"
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job_ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
