name: secrets and vairables

on:
  push:
    branches:
      - main

jobs:
  secrer-variable:
    runs-on: ubuntu-latest
    steps:
      - name: check variable
        run : echo "My app is ${{vars.APP_ID}}"
      - name: tell me a secret
        run: echo "THe secret is ${{ secrets.API_KEY }}"
      - name: get env var
        run: echo "the env var is ${{ env.APP_ID }}"