name: webhook

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  webhook-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "Event of type $GITHUB_EVENT_NAME"