name: "WorkFLow Commands"
on: ['push']
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "my group msg"
          echo "msg1"
          echo "msg2"